include:
    - variables.yml

stages:
    - prechecks
    - prebackup
    - activity
    - postbackup
    - postchecks

prechecks:
    stage: prechecks
    script:
        - echo "running prechecks"
        - sh $CI_PROJECT_DIR/scripts/healthcheck.sh
    allow_failure: false
    tags:
        - gitlab-runner

prebackup:
    stage: prebackup
    script:
        - echo "running prechecks"
        - sh $CI_PROJECT_DIR/scripts/backup.sh
    allow_failure: false
    dependencies:
        - prechecks
    tags:
        - gitlab-runner

activity:
    stage: activity
    script:
        - echo "running prechecks"
        - sh $CI_PROJECT_DIR/scripts/activity.sh
    allow_failure: false
    dependencies:
        - prebackup
    tags:
        - gitlab-runner

postbackup:
    stage: postbackup
    script:
        - echo "running postbackup"
        - sh $CI_PROJECT_DIR/scripts/backup.sh
    allow_failure: false
    dependencies:
        - activity
    tags:
        - gitlab-runner

postchecks:
    stage: postchecks
    script:
        - echo "running postchecks"
        - sh $CI_PROJECT_DIR/scripts/healthcheck.sh
    allow_failure: false
    dependencies:
        - postbackup
    tags:
        - gitlab-runner
