include:
    - variables.yml

stages:
    - prechecks
    - prebackup
    - activity
    - postbackup
    - postchecks

prechecks:
    stage: prechecks
    script:
        - echo "running prechecks"
        - sh $CI_PROJECT_DIR/scripts/healthcheck.sh
    allow_failure: false
    tags:
        - shell-runner

activity:
    stage: activity
    script:
        - echo "running prechecks"
        - sh $CI_PROJECT_DIR/scripts/activity.sh
    allow_failure: false
    dependencies:
        - prechecks
    tags:
        - shell-runner

postchecks:
    stage: postchecks
    script:
        - echo "running postchecks"
        - sh $CI_PROJECT_DIR/scripts/healthcheck.sh
    allow_failure: false
    dependencies:
        - activity
    tags:
        - shell-runner
