include:
    - variables.yml

stages:
    - prechecks
    - prebackup
    - activity
    - postbackup
    - postchecks

prechecks:
    stage: prechecks
    script:
        - echo "running prechecks"
        - sh $CI_PROJECT_DIR/scripts/prechecks.sh
    allow_failure: false
    tags:
        - shell-runner

prebackup:
    state: prebackup
    script:
        - echo "running backup"
        - sh $CI_PROJECT_DIR/scripts/backup.sh
    allow_failure: yes
    tags:
        - shell-runner

activity:
    stage: activity
    script:
        - echo "running prechecks"
        - sh $CI_PROJECT_DIR/scripts/activity.sh
    allow_failure: false
    dependencies:
        - prechecks
    tags:
        - shell-runner

postbackup:
    state: postbackup
    script:
        - echo "running backup"
        - sh $CI_PROJECT_DIR/scripts/backup.sh
    allow_failure: yes
    tags:
        - shell-runner

postchecks:
    stage: postchecks
    script:
        - echo "running postchecks"
        - sh $CI_PROJECT_DIR/scripts/postchecks.sh
    allow_failure: false
    dependencies:
        - activity
    tags:
        - shell-runner
