include:
    - variables.yml

stages:
    - prechecks
    - prebackup
    - upgrade
    - postbackup
    - postchecks

prechecks:
    stage: prechecks
    script:
        - echo "running prechecks"
        - sh $CI_PROJECT_DIR/scripts/prechecks.sh
    allow_failure: false
    tag:
        - gitlab-runner

prebackup:
    stage: prebackup
    script:
        - echo "running prechecks"
        - sh $CI_PROJECT_DIR/scripts/prebackup.sh
    allow_failure: false
    dependencies:
        - prechecks
    tag:
        - gitlab-runner

upgrade:
    stage:
    script:
        - echo "running prechecks"
        - sh $CI_PROJECT_DIR/scripts/upgrade.sh
    allow_failure: false
    dependencies:
        - prebackup
    only:
        vars:
            $activity == "upgrade"
    tag:
        - gitlab-runner

rollback:
    stage: rollback
    script:
        - echo "running rollback"
        - sh $CI_PROJECT_DIR/scripts/rollback.sh
    allow_failure: false
    dependencies:
        - prebackup
    only:
        vars:
            $activity == "rollback"
    tag:
        - gitlab-runner

postbackup:
    script:
        - echo "running postbackup"
        - sh $CI_PROJECT_DIR/scripts/prechecks.sh
    allow_failure: false
    dependencies:
        - upgrade
        - rollback
    tag:
        - gitlab-runner

postchecks:
    stage: postchecks
    script:
        - echo "running postchecks"
        - sh $CI_PROJECT_DIR/scripts/postchecks.sh
    allow_failure: false
    dependencies:
        - postbackup
    tag:
        - gitlab-runner
