---
- hosts: all
  become: yes
  tasks:
  - name: Install nginx package
    yum:
      name: "{{package}}"
      state: present
      update_cache: yes
      allow_downgrade: yes
    when: activity == "install"

  - name: Upgrade nginx package
    apt:
      name: "{{package}}"
      only_upgrade: yes
      update_cache: yes
      allow_downgrade: yes
    when: activity == "upgrade"

  - name: Rollback nginx package
    apt:
      name: "{{package}}"
      state: present
      force: yes
      update_cache: yes
    when: activity == "rollback"