---
- hosts: all
  vars:
    activity: "{{ lookup('env', 'activity') }}"
    package: "{{ lookup('env', 'package') }}"
  tasks:
  - name: install package
    yum:
      name: "{{ package }}"
      state: present
      update_cache: yes
      allow_downgrade: yes
    when: activity == "install"

  - name: upgrade package
    yum:
      name: "{{ package }}"
      state: latest
      only_upgrade: yes
      update_cache: yes
      allow_downgrade: yes
    when: activity == "upgrade"
  
  - name: remove package
    yum:
      name: "{{ package }}"
      state: absent
    when: activity == "remove"