---
- hosts: all
  #become: yes
  #become_user: centos
  vars:
    activity: "{{ lookup('env', 'activity') }}"
    package: "{{ lookup('env', 'package') }}"
  tasks:
  - name: Install nginx package
    become_method: sudo
    yum:
      name: "{{ package }}"
      state: present
      update_cache: yes
      allow_downgrade: yes
    when: activity == "install"

  - name: Upgrade nginx package
    become_method: sudo
    yum:
      name: "{{ package }}"
      only_upgrade: yes
      update_cache: yes
      allow_downgrade: yes
    when: activity != "install"

  - name: Rollback nginx package
    become_method: sudo
    yum:
      name: "{{ package }}"
      state: present
      force: yes
      update_cache: yes
    when: activity != "install"