---
- hosts: all
  become: yes
  become_user: centos
  vars:
    activity: "{{ lookup('env', 'activity') }}"
    package: "{{ lookup('env', 'package') }}"
  tasks:
  - name: create backup directory
    file:
      path: /tmp/{{ package }}
      state: directory

  - name: create backup archive of configuration directory
    copy:
      src: /etc
      dest: /tmp/{{ package }}
      remmote_src: yes

  - name: create archive
    archive:
      path: /tmp/{{ package }}
      dest: /tmp/{{ package }}.tgz

  - name: remove backup directory
    file:
      path: /tmp/{{ package }}
      state: absent