---
- hosts: all
  become: yes
  become_user: centos
  vars:
    activity: "{{ lookup('env', 'activity') }}"
    package: "{{ lookup('env', 'package') }}"
  tasks:
  - name: create backup archive of configuration directory
    archive:
      path: /etc
      dest: /tmp/{{package}}.tgz