---
- hosts: all
  vars: $CI_PROJECT_DIR/variables.yml
  tasks:
  - name: check the disk space usage
    shell: df -h
    register: result

  - name: service name
    shell: echo {{package}} | awk -F'-' '{print $1}'
    register: servicename

  - name: check the rpm version
    shell: rpm -qa | grep {{servicename.stdout}}

  - name: check the service is running
    systemd:
      name: "{{servicename.stdout}}"
      state: running
    register: result
    when: activity == "upgrade" or activity == "rollback"

  - name: check the port is listening
    shell: netstat -antp -4 | grep {{servicename.stdout}}
    register: result
    when: activity == "upgrade" or activity == "rollback"