---
- hosts: all
  vars:
    activity: "{{ lookup('env', 'activity') }}"
    package: "{{ lookup('env', 'package') }}"
  tasks:
  - name: check the disk space usage
    shell: df -h
    register: result

  - name: service name
    shell: echo {{ package }} | awk -F'-' '{print $1}'
    register: servicename

  - debug:
      var: servicename

  - name: check the rpm version
    shell: rpm -qa | grep "{{servicename}}"
    when: activity != "install"

  - name: check the service is running
    systemd:
      name: "{{servicename.stdout}}"
      state: running
    register: result
    when: activity != "install"

  - name: check the port is listening
    shell: netstat -antp -4 | grep {{servicename.stdout}}
    register: result
    when: activity != "install"