---
- hosts: all
  become: yes
  tasks:
  - name: check the disk space usage
    shell: for space in `df -h | grep -v Use% | awk '{print $5}' | awk -F'%' '{print $1}'`; do if [[ $space -ge 80 ]]; then echo "disk space exhausted"; else echo "disk space is okay"; fi; done
    register: result
    failed_when: 'exhausted' not in result.stdout

  - name: service name
    shell: echo {{package}} | awk -F'-' '{print $1}'
    register: servicename

  - name: check the rpm version
    shell: rpm -qa | grep {{service}}
    
  - name: check the service is running
    systemd:
      name: "{{servicename}}"
      state: running
    register: result
    when: activity == "upgrade" or activity == "rollback"
    failed_when: 'active (running)' not in result.stdout

  - name: check the port is listening
    shell: netstat -antp -4 | grep {{servicename}}
    register: result
    when: activity == "upgrade" or activity == "rollback"
    failed_when: 'LISTEN' not in result.stdout